import { screen } from '../test-utils';

export const getByAllRoles = (): void => {
  const roles = [
    [
      'button',
      'checkbox',
      'gridcell',
      'link',
      'menuitem',
      'menuitemcheckbox',
      'menuitemradio',
      'option',
      'progressbar',
      'radio',
      'scrollbar',
      'searchbox',
      'slider',
      'spinbutton',
      'switch',
      'tab',
      'tabpanel',
      'textbox',
      'treeitem',
    ],
    [
      'combobox',
      'grid',
      'listbox',
      'menu',
      'menubar',
      'radiogroup',
      'tablist',
      'tree',
      'treegrid',
    ],
    [
      'application',
      'article',
      'blockquote',
      'caption',
      'cell',
      'columnheader',
      'definition',
      'deletion',
      'directory',
      'document',
      'emphasis',
      'feed',
      'figure',
      'generic',
      'group',
      'heading',
      'img',
      'insertion',
      'list',
      'listitem',
      'math',
      'meter',
      'none',
      'note',
      'paragraph',
      'presentation',
      'row',
      'rowgroup',
      'rowheader',
      'separator',
      'strong',
      'subscript',
      'superscript',
      'table',
      'term',
      'time',
      'toolbar',
      'tooltip',
    ],
    [
      'banner',
      'complementary',
      'contentinfo',
      'form',
      'main',
      'navigation',
      'region',
      'search',
    ],
    ['alert', 'log', 'marquee', 'status', 'timer'],
    ['alertdialog', 'dialog'],
    ['code'],
  ];
  const roleDictEntries = roles
    .flat()
    .map<[string, HTMLElement[]]>((role) => [role, screen.queryAllByRole(role)])
    .filter(([, list]) => list.length > 0)
    .map(([role, elements]) => [role, elements.map((el) => el.innerHTML)]);
  const dict = Object.fromEntries(roleDictEntries);
  console.info(dict);
};
